/*
            **********************************************
            Title: Android Remote Control Part 1*
            Author: Daniel Ross
            Date: Feb 02, 2017
            Code version: *
            Availability: www.youtube.com/watch?v=Zgmaho84d2I&list=PL6LQDONHZvFJH6b_YFybR9Bi3nXPFhjU5&index=13.
            - The primary function of this code allowed me to get a good introduction to android studio code and
            presented a javascript alternative to open a network socket with the Raspberry pi in order to
            transmit data in real-time. **This is actually not even used within mainactivity.java but served as
            the stepping stone for the research and development
            *** THE PRIMARY FUNCTION OF THIS CODE IS TO ONLY CONTROL THE GYROSCOPE SERVO MECHANISM
	    *** This is actually a header file automatically created from a terminal command line prompt that compiles
            the javascript variables into workable C++ variables that the server can extract.
            ***************************************************
            */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Steering */

#ifndef _Included_Steering
#define _Included_Steering
#ifdef __cplusplus
extern "C" {
#endif
#undef Steering_STEERING_CENTER
#define Steering_STEERING_CENTER 1400L
#undef Steering_STEERING_RIGHT_MAX
#define Steering_STEERING_RIGHT_MAX 1130L
#undef Steering_STEERING_LEFT_MAX
#define Steering_STEERING_LEFT_MAX 1670L
#undef Steering_GPIO_PINX
#define Steering_GPIO_PINX 22L
#undef Steering_PINY
#define Steering_PINY 23L
/*
 * Class:     Steering
 * Method:    turnWheels
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Steering_turnWheels
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Steering
 * Method:    turnWheelsY
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Steering_turnWheelsY
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
